### PR TITLE
version 8

### PR DESCRIPTION
**Pull request by tprelog**
Switch to python 3.10 for new install

### CODE REVIEW

**Comment by adorobis** [comment]
Is it enough to take those files from the pull request and put them in the /root directory of the jail?

**Comment by tprelog** [comment]
> Is it enough to take those files from the pull request and put them in the /root directory of the jail?

Yes, as long as you're on at least plugin version 6  I believe it will OK -- I'm still gonna play around with making a function for updating the plugin overlay _without running_ a Plugin UPDATE.

**Comment by tprelog** [comment]
> making a function for updating the plugin overlay _without running_ a Plugin UPDATE


@adorobis  -- This should do the trick ( here we pull from `next` branch )

This will download and extract the plugin overlay to the root `/` directory  - **Make sure you run this inside the jail**

```bash
# Run from the jail's console
# Press `0` to exit the menu
curl -sL https://github.com/tprelog/iocage-homeassistant/archive/next.tar.gz | tar -xzf - -C / --strip=2 -- "*iocage-homeassistant*/overlay/"
```

After the initial update, you'll have a new `update-overlay` command for future use inside the jail.

With no options, it will pull the overlay directory from the `master` branch
```bash
# Press `0` to exit the menu
update-overlay
``` 

Or you can specify another branch of the repo, for example the `next` branch
```bash
# Press `0` to exit the menu
update-overlay next
```

Or you can pull overlay directory from the latest tagged release
```bash
# Press `0` to exit the menu
update-overlay release
```

**Comment by adorobis** [comment]
Many thanks, works like a charm (the update overlay part at least)!

**Pull request merged**
